### PR TITLE
Ensure React is available in scope

### PR DESCRIPTION
**Pull request by xtuc**
Just my 2 cents :smile:

### CODE REVIEW

**Comment by roman01la** [comment]
That's awesome! I was thinking on providing more checks like this :)
Maybe it makes sense to put this earlier in the code to prevent plugin from doing anything if there's no global `React`?

**Comment by xtuc** [comment]
> Maybe it makes sense to put this earlier in the code to prevent plugin from doing anything if there's no global React?

Yes sure, but I don't think it would make a big difference.

If you want to support React alternatives (preact for example). I would prefer the use of `Component` for extending the class. Use `React.Component` if available or else throw.

```js
import {Component} from 'preact'

// or

import {Component} from 'React'

// vs

import React from 'React'
```

**Comment by roman01la** [comment]
I think this small check is good for now, let's see if it needs more later :)
Thanks!

**Comment by xtuc** [comment]
No problem, I'm happy to help!

**Pull request merged**
